version: 0.0
os: linux
files:
  - source: /*
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: scripts/stopserver
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/startserver
      timeout: 300
      runas: root
